#!/bin/bash
#
#  Command Line Interface to start all services associated with the Getting-Started Tutorial
#
#  For this tutorial the commands are merely a convenience script to run docker-compose
#

set -e

loadData () {
	./import-data
	./provision-devices
	echo ""
}


stoppingContainers () {
	echo "Stopping containers"
	docker-compose --log-level ERROR -f docker-compose/cygnus-sth-comet.yml -p fiware down -v --remove-orphans
}

if (( $# != 1 )); then
    echo "Illegal number of parameters"
    echo "usage: services [create|cygnus|sth-comet|stop]"
    exit 1
fi

command="$1"
case "${command}" in
	"help")
        echo "usage: services [create|cygnus|sth-comet|stop]"
        ;;
	 "sth-comet")
		stoppingContainers
		echo -e "Starting five containers \033[1;34mOrion\033[0m, \033[1;34mSTH-Comet\033[0m, \033[1;36mIoT-Agent\033[0m, \033[1;30mTutorial\033[0m and a \033[1;30mMongoDB\033[0m database."	
		echo -e "- \033[1;34mOrion\033[0m is the context broker"
		echo -e "- \033[1;34mSTH-Comet\033[0m will read and write to Mongo-DB"
		echo -e "- \033[1;36mIoT-Agent\033[0m is configured for the UltraLight Protocol"
		echo -e "- \033[1;30mTutorial\033[0m acts as a series of dummy IoT Sensors over HTTP"
		echo ""
		docker-compose --log-level ERROR -f docker-compose/sth-comet.yml -p fiware up -d --remove-orphans
		loadData
		echo ""
		echo -e "Now open \033[4mhttp://localhost:3000/device/monitor\033[0m"
		;;
     "cygnus")
		stoppingContainers
		echo -e "Starting five containers \033[1;34mOrion\033[0m, \033[1;34mCygnus\033[0m, \033[1;34mSTH-Comet\033[0m, \033[1;36mIoT-Agent\033[0m, \033[1;30mTutorial\033[0m and a \033[1;30mMongoDB\033[0m database."	
		echo -e "- \033[1;34mOrion\033[0m is the context broker"
		echo -e "- \033[1;34mCygnus\033[0m is configured to write context data to Mongo-DB"
		echo -e "- \033[1;34mSTH-Comet\033[0m is reading context data from Mongo-DB"
		echo -e "- \033[1;36mIoT-Agent\033[0m is configured for the UltraLight Protocol"
		echo -e "- \033[1;30mTutorial\033[0m acts as a series of dummy IoT Sensors"
		echo ""
		docker-compose --log-level ERROR -f docker-compose/cygnus-sth-comet.yml -p fiware up -d --remove-orphans
		loadData
		echo ""
		echo -e "Now open \033[4mhttp://localhost:3000/device/monitor\033[0m"
		;;
	"stop")
		stoppingContainers
		;;
	"create")
		echo "Pulling Docker images"
		docker-compose --log-level ERROR -f docker-compose/cygnus-sth-comet.yml -p fiware pull
		;;
	*)
		echo "Command not Found."
		echo "usage: services [create|cygnus|sth-comet|stop]"
		exit 127;
		;;
esac